version: '2'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DOCKER_IMAGE=DOCKER_IMAGE
    command: bash -c 'scripts/start.sh'

  build-helper:
    image: 106251776774.dkr.ecr.ap-southeast-2.amazonaws.com/bct-build-helper:latest
    volumes:
      - ".:/app"
    environment:
      AWS_DEFAULT_REGION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_SESSION_TOKEN:
      AWS_PROFILE:
      APP_NAME:
      AWS_ACCOUNT:
      BUILDKITE:
      COMMIT:
      OWNER:
      ENVIRONMENT:
      PROJECT:
    working_dir: /app
